### ISSUE TITLE
cam2image__rmw_connext_cpp fails

### ISSUE THREAD

**Issue by jacquelinekay** [ros2/demos#61] opened 2016-02-18 00:09 UTC
Running showimage in another terminal, if I start cam2image I get the error:

```
Publishing image #1
COMMENDSrWriterService_write:!write. Reliable large data requires asynchronous writer.
PRESPsWriter_writeInternal:!srw->write
terminate called after throwing an instance of 'std::runtime_error'
  what():  failed to publish message: failed to publish message, at /home/jackie/code/ros2_ws/src/ros2/rmw_connext/rmw_connext_cpp/src/functions.cpp:410
Aborted (core dumped)
```

**Comment by jacquelinekay** [comment] 2016-02-18 00:12
As you might expect, running the demo with `-r 0` causes it to work

**Comment by mikaelarguedas** [comment] 2017-02-01 01:47
dunno when that was fixed but it was not reported in recent release testing and cant reproduce locally. 
If anybody can confirm we can close this and update tutorial page accordingly

**Comment by dhood** [comment] 2017-04-26 23:33
closing this because tests for these executables were added in https://github.com/ros2/demos/pull/83

**Closed by dhood** 2017-04-26 23:33 UTC
